### ISSUE TITLE
Add link to help site

### ISSUE THREAD

**Issue by davidkassa** [bitwarden/website#14]
Consider adding a link to the help site. I didn't know it existed until I started looking at the github repos.

**Comment by davidkassa** [comment]
Also the blog

**Comment by kspearrin** [comment]
Yes, this will be part of a larger website re-design in the near future.

**Comment by getreadyforme** [comment]
Hello, I was going to post the same exact request.  Right now we can only access the help area from the browser extension, or after logging into the website.  I think the help should be readily available on the main page for all users without login.   

Regardless of any plans to re-design, for the time being would you please add a link to https://help.bitwarden.com/  on the main site https://bitwarden.com/ ?
This way all users can access the tutorials, e.g. how to import account data from Lastpass, and other topics.  

Thank you.

**Comment by kspearrin** [comment]
We have a new redesign site rolling out at end of the month which will include this.
