### ISSUE TITLE
Friendly suggestion to consider not using bit.ly with a shell script

### ISSUE THREAD

**Issue by ghost** [bitwarden/website#18]
Right now https://bit.ly/bw-sh redirects to github.

But that's one additional party to trust (bit.ly).

Self hosting the script would maybe be ideal, but even something like:

https://bitwarden.com/sh (redirecting to github)

Would only be 4 characters more. And it would cut out one more middle man to trust.

I know this happened 3 years ago, but these things do happen: https://twitter.com/Bitly/statuses/464561181504839680

Just an idea :-)

**Comment by kspearrin** [comment]
This was done so we could get the short URL to fit on the homepage callout. The main install docs do not include this.

**Comment by kspearrin** [comment]
Changed to our own URL shortener now.
