### ISSUE TITLE
Write bitwarden from capital letter? (Bitwarden or BitWarden)?

### ISSUE THREAD

**Issue by Lisennk** [bitwarden/website#2]
"bitwarden" word from small letter looks ugly

**Comment by joshsleeper** [comment]
I disagree and personally like it being completely lowercase, but it's a matter of preference.

If nothing else, this should probably be labeled as an enhancement and see if any other users weigh in on the subject.

**Comment by kspearrin** [comment]
This is subjective. The lowercase word is part of our brand at this point.
