### ISSUE TITLE
community.bitwarden.com doesn't trigger browser extension to save the password

### ISSUE THREAD

**Issue by arcooke** [bitwarden/website#25]
I just signed up on community.bitwarden.com to submit a feature request and noticed the website doesn't seem to trigger the browser extension (Firefox Nightly in my case) to save my password.  Not during sign-up, and not even if I log out and log back in.  

I thought that was kind of amusing since this feature seems to work fine on every other website except Bitwarden's own forums 

Just a heads up

**Comment by kspearrin** [comment]
Thanks. It's fixed for next browser extension release.
