### ISSUE TITLE
[Feature] Accept Cryptocurrency

### ISSUE THREAD

**Issue by asddsaz** [bitwarden/website#28]
**Feature**: Accept Cryptocurrency for Premium Accounts
**How?** I would recommend using [Changelly](https://changelly.com/for-services) and/or [KyberNetwork](https://kyber.network/faq?type=dln) with [Coinbase](https://commerce.coinbase.com/) for liquidation.

**Comment by ProgressiveArchitect** [comment]
I second this. You market yourself as a privacy focused Password Manager and you have now built up a network of very strong supporters of the Bitwarden software including myself. However, for a provider to be truly private, the customers/users need to be able to pay in a private way, Which currently doesn't exist for Bitwarden. Here are two popular services that are easy to integrate into merchant/provider websites like bitwarden.com. https://bitpay.com/ & https://www.coinpayments.net/

**Comment by kspearrin** [comment]
Done

**Comment by User486375** [comment]
@kspearrin Are there any plans in the future to support more privacy centric coins? E.g. Zcash and Monero.
