### ISSUE TITLE
Dynamic timestamp in footer shows the year 2019

### ISSUE THREAD

**Issue by danguenet** [bitwarden/website#40]
File: website/_layouts/default.html
Code: `{{ 'now' | date: "%Y" }}`

Nothing is wrong with the code. It just uses the year from when the website was last built.

**Comment by danguenet** [comment]
I can create a pull request, but it felt odd to make one with no edits. 

I think this should work if there are no desired edits:
`git commit -m 'rebuild pages' --allow-empty
git push origin master`

**Comment by kspearrin** [comment]
Fixed. Just needed to re-deploy. Thanks.
