### ISSUE TITLE
Login email validator does not properly validate

### ISSUE THREAD

**Issue by pkarjala** [bitwarden/website#7]
At https://vault.bitwarden.com/#/login, when typing in an email address before submitting the form, the only requirement is that there is an "@" symbol present.  It does not actually validate whether it is a properly formatted email address before submitting to the back end and returning a validation error.

This allows submissions such as "test@test".

This also affects the registration page at https://vault.bitwarden.com/#/register

**Comment by kspearrin** [comment]
This is not the correct repo for this. This is something that would belong in the "web" repo.

**Comment by pkarjala** [comment]
Migrated to https://github.com/bitwarden/web/issues/9
