### ISSUE TITLE
Use before-submission validation on Registration page

### ISSUE THREAD

**Issue by pkarjala** [bitwarden/website#8]
There is little immediate validation done on the registration page beyond the email address before pressing the submit button.  It is a best practice to do immediate validation and provide feedback for things such as:

- Email address
- Matching passwords
- Length / strength of passwords

**Comment by kspearrin** [comment]
This is not the correct repo for this. This is something that would belong in the "web" repo.

**Comment by pkarjala** [comment]
Migrated to https://github.com/bitwarden/web/issues/8
