### ISSUE TITLE
Add increasing timeouts on login failure

### ISSUE THREAD

**Issue by pkarjala** [bitwarden/website#9]
Currently there is about a 2 second timeout on login failure.  I'd recommend using an increasing timeout based on IP address that prevents too many failed logins, and requires the user to wait 5 minutes after too many failed attempts.  This is an important feature for a site that will host user passwords.

**Comment by kspearrin** [comment]
This is not the correct repo for this request. This would be something related to the core project.

**Comment by pkarjala** [comment]
Migrated to https://github.com/bitwarden/core/issues/16
